// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iywbhfqnisfgwfythnna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5d2JoZnFuaXNmZ3dmeXRobm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTg1MzksImV4cCI6MjA2NTk3NDUzOX0.dzzV0luOQN72Jg0CchlZqjsl8ieZqq-dgMyKBlch6GQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);